spring.application.name=careerportal
spring.datasource.url=jdbc:postgresql://localhost:5432/career_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

openrouter.api.key=${OPENROUTER_API_KEY}

